# Generated by Django 4.1.3 on 2022-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('MI', 'Miscellaneous'), ('FR', 'Fruit'), ('VG', 'Vegetable'), ('SP', 'Spice'), ('HE', 'Herb'), ('DY', 'Dairy'), ('CH', 'Chicken'), ('BF', 'Beef'), ('CH', 'Cheese'), ('FU', 'Mushroom'), ('OI', 'Oil'), ('FL', 'Flour'), ('PE', 'Peanut'), ('NU', 'Tree Nut')], default='MI', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['step_no']},
        ),
    ]
