# Generated by Django 4.1.3 on 2022-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ingredient_alter_instruction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('MI', 'Miscellaneous'), ('FR', 'Fruit'), ('VG', 'Vegetable'), ('SP', 'Spice'), ('HE', 'Herb'), ('DY', 'Dairy'), ('CH', 'Poultry'), ('BF', 'Beef'), ('CH', 'Cheese'), ('FU', 'Mushroom'), ('OI', 'Oil'), ('FL', 'Flour'), ('PE', 'Peanut'), ('NU', 'Tree Nut')], default='MI', max_length=2),
        ),
    ]
